Repository LunarVim/starter.lvim, pull requests merged in 2022-10, with the labels that each got.

#10 minimal ide setup for c/c++
  README.md
  config.lua
Labels: HACKTOBERFEST-ACCEPTED

#9 feat: add python-ide starter pack
  README.md
  config.lua
  requirements.txt
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#14 fix(c-ide): errors regarding multiple client offset_encoding
  config.lua
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#22 update for c-ide
  config.lua
Labels: enhancement, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#15 [Hacktoberfest] Go IDE feature
  .gitignore
  README.md
  config.lua
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#23 basic elixir-ide setup
  README.md
  config.lua
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#19 Scala IDE
  README.md
  config.lua
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#21 [Hacktoberfest] PHP IDE feature
  .gitignore
  README.md
  config.lua
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#16 Rust IDE
  README.md
  config.lua
Labels: enhancement, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#28 Fix(java-ide): Add missing on_attach functionality
  ftplugin/java.lua
Labels: HACKTOBERFEST-ACCEPTED

#36 fix(java-ide): Make keymaps buffer specific
  README.md
  ftplugin/java.lua
Labels: HACKTOBERFEST-ACCEPTED

#37 fix(go-ide): Make keymaps buffer specific
  config.lua
Labels: HACKTOBERFEST-ACCEPTED

#38 fix: Add .stylua.toml from Lunarvim/lunarvim
  .stylua.toml
Labels: HACKTOBERFEST-ACCEPTED

#33 feat(latex-ide): basic latex config
  config.lua
  lua/user/cmp.lua
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED
